/* Generated by gen.js — do not edit by hand. */
window.MG_ITEMS = [
 {
  "n": 1,
  "no": "1-1",
  "file": "f001.html",
  "g": "1. Basic structure",
  "t": "Creating a grid — one div is enough",
  "d": "Put an empty &lt;div&gt; on the page and call ModuGrid(selector, {cols}). The table, footer, popups, modals and toast are all built by the grid itself, so there is no markup for you to prepare."
 },
 {
  "n": 2,
  "no": "1-2",
  "file": "f002.html",
  "g": "1. Basic structure",
  "t": "Several grids on one page — themes and fonts too",
  "d": "Grids never interfere with each other. Sorting and selection are separate, and so are themes and fonts, which makes it easy to place two very different tables side by side."
 },
 {
  "n": 3,
  "no": "1-3",
  "file": "f003.html",
  "g": "1. Basic structure",
  "t": "Taking a grid off the page — destroy()",
  "d": "Call destroy() when you close a tab or swap the screen out. The grid releases its listeners and clears the DOM it created. Skip it and the keyboard handlers stay behind."
 },
 {
  "n": 4,
  "no": "2.3-1",
  "file": "f004.html",
  "g": "2.3 System columns",
  "t": "Row number, status and checkbox columns (_rn · _st · _cb)",
  "d": "_rn (row number), _st (change status) and _cb (checkbox) only need to appear in cols. Wherever you declare them they end up on the far left and stay put when you scroll sideways."
 },
 {
  "n": 5,
  "no": "2.3-2",
  "file": "f005.html",
  "g": "2.3 System columns",
  "t": "Recolouring the row gutter (--bg-gut)",
  "d": "The system columns use a different background in the body, the way Excel shades its row gutter. If the shade does not suit your screen, change the single --bg-gut variable."
 },
 {
  "n": 6,
  "no": "2.4-1",
  "file": "f006.html",
  "g": "2.4 Manipulating columns",
  "t": "Adding, removing and changing columns from code",
  "d": "Columns can change without rebuilding the screen, which is what you want when the visible fields depend on a role or a search condition. A new column goes at the end, at an index, or before a named column."
 },
 {
  "n": 7,
  "no": "2.4-2",
  "file": "f007.html",
  "g": "2.4 Manipulating columns",
  "t": "A column key cannot be changed",
  "d": "updateCol() will change the label, width and type, but never the key. The key is the link between a column and the data, so changing it would break every value in that column. If you really need a different key, remove the column and add it again."
 },
 {
  "n": 8,
  "no": "2.4-3",
  "file": "f008.html",
  "g": "2.4 Manipulating columns",
  "t": "Being told when columns change — dataChange {type:'cols'}",
  "d": "Every change to the column set fires dataChange with type:'cols'. Listen for it if you keep a saved layout that needs refreshing."
 },
 {
  "n": 9,
  "no": "2.5-1",
  "file": "f114.html",
  "g": "2.5 Custom cells",
  "t": "Custom cells — render(value, row, ctx) and cellClick",
  "d": "Whatever HTML render returns goes into the cell as-is, so a cell can hold bars, tags or buttons. The third argument carries the column, which lets one formatter serve several columns, and cellClick reports the element that was actually pressed."
 },
 {
  "n": 10,
  "no": "3.1-1",
  "file": "f009.html",
  "g": "3.1 Sorting",
  "t": "Sorting is done with the ▲▼ icons",
  "d": "Click the ▲▼ icons at the right of a header to sort. The header label is reserved for moving the column, so dragging the text reorders the columns instead."
 },
 {
  "n": 11,
  "no": "3.1-2",
  "file": "f010.html",
  "g": "3.1 Sorting",
  "t": "Ascending → descending → off",
  "d": "Each click of a sort icon moves through ascending, descending and off. Turning it off restores the order the data arrived in."
 },
 {
  "n": 12,
  "no": "3.1-3",
  "file": "f011.html",
  "g": "3.1 Sorting",
  "t": "Which column is sorted",
  "d": "Only the sorted column shows a solid arrow and an emphasised label, so you can tell at a glance where the ordering comes from."
 },
 {
  "n": 13,
  "no": "3.1-4",
  "file": "f012.html",
  "g": "3.1 Sorting",
  "t": "Sorting on several columns",
  "d": "Pass multiSort:true and sorts stack up. Each column gets a 1, 2, 3 order badge in the order you clicked, and each one cycles through ascending, descending and off on its own."
 },
 {
  "n": 14,
  "no": "3.1-5",
  "file": "f013.html",
  "g": "3.1 Sorting",
  "t": "Removing sorts from the sort bar",
  "d": "A sort bar appears above the grid as soon as anything is sorted. Drop one condition with the ✕ on its chip, or clear the lot with Clear."
 },
 {
  "n": 15,
  "no": "3.2-1",
  "file": "f014.html",
  "g": "3.2 Filtering",
  "t": "Picking values to show",
  "d": "The funnel icon on a header opens the list of values actually present in that column. Tick the ones you want and press Apply."
 },
 {
  "n": 16,
  "no": "3.2-2",
  "file": "f015.html",
  "g": "3.2 Filtering",
  "t": "Select all in the filter popup",
  "d": "The Select all box at the top of the popup has three states — everything ticked, some ticked (shown as an indeterminate mark) and nothing ticked. The selected / total count sits beside it."
 },
 {
  "n": 17,
  "no": "3.2-3",
  "file": "f016.html",
  "g": "3.2 Filtering",
  "t": "Finding a value in a long list",
  "d": "A column with many distinct values gets a search box at the top of the popup. While a search is active, Select all only touches the entries you can see, so anything hidden keeps its current state."
 },
 {
  "n": 18,
  "no": "3.2-4",
  "file": "f017.html",
  "g": "3.2 Filtering",
  "t": "Filtering a numeric range",
  "d": "Number, currency and progress columns offer min and max boxes instead of a value list. The actual range found in the data is printed underneath as a hint."
 },
 {
  "n": 19,
  "no": "3.2-5",
  "file": "f018.html",
  "g": "3.2 Filtering",
  "t": "Spotting which columns are filtered",
  "d": "A small dot appears on the header of any column with an active condition, which saves hunting through a wide table."
 },
 {
  "n": 20,
  "no": "3.2-6",
  "file": "f019.html",
  "g": "3.2 Filtering",
  "t": "Turning filtering off altogether",
  "d": "On a read-only screen you may not want filtering at all — showFilter:false removes it. Switching it off also clears any conditions already applied, so every row comes back."
 },
 {
  "n": 21,
  "no": "3.2-7",
  "file": "f020.html",
  "g": "3.2 Filtering",
  "t": "Leaving one column out (noFilter)",
  "d": "Adding noFilter:1 to a column definition removes just that funnel. It suits free-text columns such as a note, where every value is different and a list would be useless."
 },
 {
  "n": 22,
  "no": "3.3-1",
  "file": "f021.html",
  "g": "3.3 Search",
  "t": "Searching by code or by display name",
  "d": "search(q) sweeps several columns at once. For coded columns it matches both the display name on screen and the code stored underneath, so it finds the row whichever one the user remembers."
 },
 {
  "n": 23,
  "no": "3.4-1",
  "file": "f022.html",
  "g": "3.4 Grouping and tree",
  "t": "Grouping rows with totals",
  "d": "Rows are gathered by the value of a column and each group gets a header carrying count, average and sum. It gives you a per-department headcount and salary total without building a separate screen."
 },
 {
  "n": 24,
  "no": "3.4-2",
  "file": "f023.html",
  "g": "3.4 Grouping and tree",
  "t": "Showing a hierarchy as a tree",
  "d": "Point each row at its parent with parentId and mark rows that have children with _hc:true. Use it for org charts, category trees, bills of materials — anything with a parent and child relationship."
 },
 {
  "n": 25,
  "no": "4-1",
  "file": "f024.html",
  "g": "4. Selection",
  "t": "Clicking a row and ticking it are two different things",
  "d": "Rows you click and rows you tick are kept as separate lists. That lets you treat one as \"what I am looking at\" and the other as \"what I am about to act on\" — browse by clicking, tick the few you actually need."
 },
 {
  "n": 26,
  "no": "4-2",
  "file": "f025.html",
  "g": "4. Selection",
  "t": "The select-all checkbox",
  "d": "The checkbox in the _cb header has three states — all ticked, some ticked (an in-between mark) and none ticked — so the header alone tells you how much is selected."
 },
 {
  "n": 27,
  "no": "4-3",
  "file": "f026.html",
  "g": "4. Selection",
  "t": "The header follows the rows immediately",
  "d": "Every time you tick or untick a row the header mark is brought up to date. Tick the last outstanding row and the header fills in; untick any one and it drops back to the in-between state."
 },
 {
  "n": 28,
  "no": "4-4",
  "file": "f027.html",
  "g": "4. Selection",
  "t": "Select all covers the rows you can see",
  "d": "The header checkbox works on the rows currently rendered — the current page under ordinary paging, or the surviving rows when a filter is on. Rows you cannot see are never swept up by accident."
 },
 {
  "n": 29,
  "no": "4-5",
  "file": "f028.html",
  "g": "4. Selection",
  "t": "Putting a word in the checkbox header (cbHeader)",
  "d": "Replace the select-all checkbox with a label such as Select. It suits screens where an accidental select-all would be expensive."
 },
 {
  "n": 30,
  "no": "4-6",
  "file": "f029.html",
  "g": "4. Selection",
  "t": "Leaving the header blank (cbHeader:false)",
  "d": "Passing 'none' or false empties the header cell. It is the surest way to keep select-all off the screen entirely."
 },
 {
  "n": 31,
  "no": "4-7",
  "file": "f030.html",
  "g": "4. Selection",
  "t": "Select all from your own toolbar — toggleCheckAll()",
  "d": "Call toggleCheckAll(true/false) from a button of your own. The result is the same as clicking the header, and so is the scope: the rows currently on screen."
 },
 {
  "n": 32,
  "no": "4-8",
  "file": "f031.html",
  "g": "4. Selection",
  "t": "Extending a range with Shift and the arrow keys",
  "d": "In cell mode this grows a rectangular block the way a spreadsheet does; in row mode it grows a run of rows. A range you started with the mouse can be extended from the keyboard."
 },
 {
  "n": 33,
  "no": "4-9",
  "file": "f032.html",
  "g": "4. Selection",
  "t": "Reading the selection — arrays of ids",
  "d": "getSelected() and getChecked() hand back arrays of ids. That is what you want to post to a server; when you need the row contents, look them up in getFilteredData()."
 },
 {
  "n": 34,
  "no": "5.1-1",
  "file": "f033.html",
  "g": "5.1 Entry points",
  "t": "Three ways to start editing a cell",
  "d": "With editMode on, editing begins on a double-click, on F2, or simply by typing. All three open the same editor, so the cell never shifts under your hands."
 },
 {
  "n": 35,
  "no": "5.1-2",
  "file": "f034.html",
  "g": "5.1 Entry points",
  "t": "One click, then type",
  "d": "Click a cell once and start typing — the input goes straight in, the way a spreadsheet behaves. There is no edit button to press first, and it works the same in row mode as in cell mode."
 },
 {
  "n": 36,
  "no": "5.1-3",
  "file": "f035.html",
  "g": "5.1 Entry points",
  "t": "Clicking another cell saves what you typed",
  "d": "If you wander off to another cell in the middle of an edit, what you had typed is committed first and the editor follows you across. Nothing is lost for want of pressing Enter."
 },
 {
  "n": 37,
  "no": "5.1-4",
  "file": "f036.html",
  "g": "5.1 Entry points",
  "t": "Tab and Shift+Tab — moving sideways",
  "d": "Tab commits the value and moves right, Shift+Tab moves left. At the end of a row it carries on to the next one, which makes filling a row at a time straightforward."
 },
 {
  "n": 38,
  "no": "5.1-5",
  "file": "f037.html",
  "g": "5.1 Entry points",
  "t": "Enter moves down · Esc cancels",
  "d": "Enter commits and moves down, Shift+Enter moves up. Esc throws away what you typed and puts the original value back."
 },
 {
  "n": 39,
  "no": "5.1-6",
  "file": "f038.html",
  "g": "5.1 Entry points",
  "t": "Delete clears cells — a whole range at once",
  "d": "Delete empties the current cell, or the entire selected range if you have one. It counts as a single step, so one Ctrl+Z brings everything back."
 },
 {
  "n": 40,
  "no": "5.1-7",
  "file": "f039.html",
  "g": "5.1 Entry points",
  "t": "A cleared number is empty, not zero",
  "d": "Clearing a numeric cell with Delete stores an empty value (null) rather than 0, because a server usually needs to tell \"scored nothing\" apart from \"not filled in yet\"."
 },
 {
  "n": 41,
  "no": "5.2-1",
  "file": "f040.html",
  "g": "5.2 Edit permissions",
  "t": "Separate permissions for insert, update and delete",
  "d": "canInsert · canUpdate · canDelete split the three rights apart. Entries the user is not allowed to use disappear from the right-click menu, and without update rights the edit modal opens read-only instead."
 },
 {
  "n": 42,
  "no": "5.2-2",
  "file": "f041.html",
  "g": "5.2 Edit permissions",
  "t": "Locking individual rows and cells",
  "d": "Lock a whole row when its status is closed, or lock one cell when the figure belongs to somebody else. Use both together and the row lock is applied first."
 },
 {
  "n": 43,
  "no": "5.2-3",
  "file": "f042.html",
  "g": "5.2 Edit permissions",
  "t": "What a lock stops, and what it does not",
  "d": "A lock applies to everything the user does on screen. It deliberately does not block updateRow() and other programmatic calls, since your code still has to apply server responses and run batch updates."
 },
 {
  "n": 44,
  "no": "5.3-1",
  "file": "f043.html",
  "g": "5.3 Input control",
  "t": "Forcing upper or lower case",
  "d": "textCase folds what the user types into upper or lower case. Use it to keep reference codes upper case and e-mail addresses lower case. It can be set on one column or across the grid."
 },
 {
  "n": 45,
  "no": "5.3-2",
  "file": "f044.html",
  "g": "5.3 Input control",
  "t": "Hints in empty cells (placeholder)",
  "d": "An empty cell can carry a hint such as Enter a name. There are three settings — every empty cell, the first row only, or nothing at all. Showing it on the first row keeps the screen calm while still explaining what belongs where."
 },
 {
  "n": 46,
  "no": "5.3-3",
  "file": "f045.html",
  "g": "5.3 Input control",
  "t": "Adding, inserting and deleting rows",
  "d": "addRow() appends at the end; insertAt() puts a row above or below the selected one. The Insert Above and Insert Below entries in the right-click menu call exactly the same thing."
 },
 {
  "n": 47,
  "no": "5.3-4",
  "file": "f046.html",
  "g": "5.3 Input control",
  "t": "Reordering rows and changing row heights",
  "d": "Drag the # cell up or down to move a row. Drag its lower edge and that one row grows taller, which is handy when a note runs long."
 },
 {
  "n": 48,
  "no": "6-1",
  "file": "f047.html",
  "g": "6. Coded values",
  "t": "Codes in the data, names on the screen",
  "d": "This is the classic lookup-table arrangement — the code is stored, the name is shown. The shape of your option list hardly matters: {code,name}, {value,label}, {id,text}, {v,t} and plain strings are all recognised."
 },
 {
  "n": 49,
  "no": "6-2",
  "file": "f048.html",
  "g": "6. Coded values",
  "t": "Deciding how a value reads (optionFormat)",
  "d": "Put placeholders such as {code} {name} into optionFormat to shape what appears. Any other field on the option object can be used too, so a department name or a headcount can travel with the value."
 },
 {
  "n": 50,
  "no": "6-3",
  "file": "f049.html",
  "g": "6. Coded values",
  "t": "Names follow the value everywhere — search, CSV and copy",
  "d": "The code-and-name split is not applied in one place only. Cells, dropdowns, autocomplete, the filter popup, search, CSV export and the Excel copy all follow the same rule, so a file never comes out full of raw codes."
 },
 {
  "n": 51,
  "no": "6-4",
  "file": "f050.html",
  "g": "6. Coded values",
  "t": "Typing to find a value in the dropdown",
  "d": "Open a cell, start typing and the list narrows. It matches on the formatted text, the display name and the code, so whichever of the three the user has in mind will find the entry."
 },
 {
  "n": 52,
  "no": "6-5",
  "file": "f051.html",
  "g": "6. Coded values",
  "t": "A value outside the list is still accepted",
  "d": "Typing something the list does not contain stores it as typed, so nobody is blocked by a lookup table that has not caught up yet. The list itself is left alone, so the next time you open the cell you see the original entries."
 },
 {
  "n": 53,
  "no": "6-6",
  "file": "f052.html",
  "g": "6. Coded values",
  "t": "Autocomplete",
  "d": "Use this when the list is far too long for a dropdown. As the user types, candidates are fetched from the server; picking one stores the code in the data and shows the name on screen. Because the grid remembers the name it was given, the label survives even though the value was never in options."
 },
 {
  "n": 54,
  "no": "6-7",
  "file": "f053.html",
  "g": "6. Coded values",
  "t": "Autocomplete settings — source, size and switching it off",
  "d": "Candidates come from the server (acSource) or from a local list (acHints). If the server does not answer, the local list stands in; a query already asked is not asked again. Columns that do not need it are switched off with ac:false."
 },
 {
  "n": 55,
  "no": "6-8",
  "file": "f054.html",
  "g": "6. Coded values",
  "t": "Reducing to codes before sending — toCode()",
  "d": "Data arriving from another screen sometimes carries the whole option object instead of the code. Send that as it is and the server receives [object Object]. toCode() pulls the code out; toCodeRow() returns a tidied copy and leaves your original untouched."
 },
 {
  "n": 56,
  "no": "7-1",
  "file": "f055.html",
  "g": "7. Validation",
  "t": "Checking input without throwing it away",
  "d": "Attach a validate function to a column and the value is checked as it is committed. A value that fails is kept and the cell is simply marked red — wiping the input would leave the user with nothing to correct and no idea what went wrong."
 },
 {
  "n": 57,
  "no": "7-2",
  "file": "f056.html",
  "g": "7. Validation",
  "t": "The same check on every route in",
  "d": "Whether the value is typed into the cell, chosen from the calendar or saved from the modal, the check runs once and to the same rules. No route quietly skips it."
 },
 {
  "n": 58,
  "no": "7-3",
  "file": "f057.html",
  "g": "7. Validation",
  "t": "Checking before you save — isValid()",
  "d": "Guard your save button with isValid() and collect the offending cells from getInvalidCells() to show the user. It is the standard step before anything goes to the server."
 },
 {
  "n": 59,
  "no": "7-4",
  "file": "f058.html",
  "g": "7. Validation",
  "t": "How long the error tooltip stays",
  "d": "An invalid value raises a ⚠ message tooltip that fades after a while — three seconds by default, adjustable with errorMsgDuration. Pass zero or less and it stays until the value is fixed."
 },
 {
  "n": 60,
  "no": "8-1",
  "file": "f059.html",
  "g": "8. Change tracking",
  "t": "Picking out what actually changed",
  "d": "Whatever the user did and however they did it, the grid compares the current state against the state it started from and reports only the differences. Cell edits, modal saves, insertions, deletions and even undo are all picked up."
 },
 {
  "n": 61,
  "no": "8-2",
  "file": "f060.html",
  "g": "8. Change tracking",
  "t": "What submit sends — checking the JSON",
  "d": "This page shows exactly what leaves for the server. It arrives in three parts — inserted carries whole rows, updated is {id, changes} with only the fields that moved, and deleted is an array of ids. Coded columns go out as codes, and stray option objects are reduced on the way."
 },
 {
  "n": 62,
  "no": "8-3",
  "file": "f061.html",
  "g": "8. Change tracking",
  "t": "Choosing which fields to send — submitFields",
  "d": "Leave it unset and the fields are derived from the columns on screen. Name them in submitFields when you want to send less than that."
 },
 {
  "n": 63,
  "no": "8-4",
  "file": "f062.html",
  "g": "8. Change tracking",
  "t": "An update carries only the fields that moved",
  "d": "Rather than the whole row, updated holds just the values that changed (alongside the id). It drops straight into the SET clause of an UPDATE, which keeps the server side short."
 },
 {
  "n": 64,
  "no": "8-5",
  "file": "f063.html",
  "g": "8. Change tracking",
  "t": "New rows follow the column order",
  "d": "The JSON for an inserted row is written in the order the columns appear, which makes the payload easy to read in a log and easy to map field by field on the server."
 },
 {
  "n": 65,
  "no": "8-6",
  "file": "f064.html",
  "g": "8. Change tracking",
  "t": "Deleting without removing (soft delete)",
  "d": "By default a deleted row stays on screen with a line through it. It is removed for real only once submit() has succeeded, which leaves room to undo a mistake."
 },
 {
  "n": 66,
  "no": "8-7",
  "file": "f065.html",
  "g": "8. Change tracking",
  "t": "Confirmation only when it cannot be undone",
  "d": "With soft delete there is a way back, so nothing is asked. Only softDelete:false, which removes the row on the spot, raises a confirmation. deleteRows() is a programmatic call and never asks either way."
 },
 {
  "n": 67,
  "no": "8-8",
  "file": "f066.html",
  "g": "8. Change tracking",
  "t": "Rows pending deletion cannot be edited",
  "d": "A row marked for deletion is closed to editing, since there is little point correcting something on its way out. Ticking and selecting still work, because that is how you bring it back."
 },
 {
  "n": 68,
  "no": "8-9",
  "file": "f067.html",
  "g": "8. Change tracking",
  "t": "Undoing a deletion — Ctrl+Z works too",
  "d": "Delete something by mistake and Ctrl+Z puts it back. To recover several rows at once, tick them and call restoreRows()."
 },
 {
  "n": 69,
  "no": "8-10",
  "file": "f068.html",
  "g": "8. Change tracking",
  "t": "Turning the change colours off (dirtyMark)",
  "d": "New rows are shaded green, edited ones amber and deleted ones red. If that is too much, dirtyMark turns the shading off — but the deletion strikethrough stays, because a row on its way out has to be visible."
 },
 {
  "n": 70,
  "no": "8.1-1",
  "file": "f069.html",
  "g": "8.1 Image transfer",
  "t": "Choosing how photos reach the server (imageMode)",
  "d": "This setting decides when a photo is uploaded and in what shape it travels. Preview only? none. Large files? upload. One save for everything? multipart. Something small like a signature? base64."
 },
 {
  "n": 71,
  "no": "8.1-2",
  "file": "f070.html",
  "g": "8.1 Image transfer",
  "t": "Limits on size and number",
  "d": "imageMaxSize caps each file and imageLimit caps the row. A file over the limit is left out on its own — everything else still goes in, and a message explains what happened."
 },
 {
  "n": 72,
  "no": "8.1-3",
  "file": "f071.html",
  "g": "8.1 Image transfer",
  "t": "none — not sending photos at all",
  "d": "Photos are shown on screen and never sent anywhere. This is the default, and in this mode the images field is left out of the payload entirely."
 },
 {
  "n": 73,
  "no": "8.1-4",
  "file": "f072.html",
  "g": "8.1 Image transfer",
  "t": "upload — sending each file as it is picked",
  "d": "The file goes to the server the moment it is chosen, and the {id, url} that comes back replaces it. When you save, only the reference travels, so a heavy set of photos does not make the save heavy."
 },
 {
  "n": 74,
  "no": "8.1-5",
  "file": "f073.html",
  "g": "8.1 Image transfer",
  "t": "upload — imageUpload is required",
  "d": "Choose upload and forget imageUpload and nothing is uploaded at all. A warning is written to the browser console, so that is the first thing to check when photos refuse to go."
 },
 {
  "n": 75,
  "no": "8.1-6",
  "file": "f074.html",
  "g": "8.1 Image transfer",
  "t": "upload — waiting for the uploads to finish",
  "d": "Save while an upload is still running and the reference goes out empty. Guard the save button with hasPendingUploads()."
 },
 {
  "n": 76,
  "no": "8.1-7",
  "file": "f075.html",
  "g": "8.1 Image transfer",
  "t": "multipart — data and files in one save",
  "d": "The files are held until you save, then the changes and the files travel together. Nobody leaves orphaned uploads behind on the server, which makes this the tidiest option when one save should do everything."
 },
 {
  "n": 77,
  "no": "8.1-8",
  "file": "f076.html",
  "g": "8.1 Image transfer",
  "t": "multipart — how the file parts are named",
  "d": "Each file is sent under the name img_{rowId}_{columnKey}_{index}. The first photo on row 3 arrives as img_3_images_0, and that is the name the server asks for."
 },
 {
  "n": 78,
  "no": "8.1-9",
  "file": "f077.html",
  "g": "8.1 Image transfer",
  "t": "multipart — finding the file by ref, and leaving Content-Type alone",
  "d": "The ref on an image entry in the JSON is the file part name, so the server reads ref and asks for that part. One caution: do not set Content-Type yourself — the browser has to add the boundary along with it."
 },
 {
  "n": 79,
  "no": "8.1-10",
  "file": "f078.html",
  "g": "8.1 Image transfer",
  "t": "multipart — files are released once the save succeeds",
  "d": "A successful save lets go of the original files. Nothing piles up in memory as you carry on working, and a photo already sent is not sent again with the next save."
 },
 {
  "n": 80,
  "no": "8.1-11",
  "file": "f079.html",
  "g": "8.1 Image transfer",
  "t": "base64 — carrying the photo inside the JSON",
  "d": "The photo is turned into text and travels inside the JSON. There is no file upload to build on the server, but the payload grows by roughly a third. Keep it for small, few items such as signatures and icons, and always set imageMaxSize alongside it."
 },
 {
  "n": 81,
  "no": "9-1",
  "file": "f080.html",
  "g": "9. Copy and export",
  "t": "Copying to Excel and exporting CSV",
  "d": "Select a range and press Ctrl+C, or use Copy Row(Excel) from the right-click menu, and paste straight into a spreadsheet. exportCSV() writes a file instead. Both follow the same rule: coded columns give their display names, numbers and money go out unformatted, so the figures are ready to calculate with."
 },
 {
  "n": 82,
  "no": "9-2",
  "file": "f081.html",
  "g": "9. Copy and export",
  "t": "Pasting a block — one undo puts it back",
  "d": "A block copied out of a spreadsheet pastes in with Ctrl+V. However many cells it fills, a single Ctrl+Z undoes the whole thing."
 },
 {
  "n": 83,
  "no": "9-3",
  "file": "f082.html",
  "g": "9. Copy and export",
  "t": "Cells that cannot take a value are skipped",
  "d": "A paste steps over what it cannot write and tells you how many cells it filled. Values failing validation, editor:false columns, rows pending deletion and anything past the last column are all skipped, and the rest of the paste carries on."
 },
 {
  "n": 84,
  "no": "10-1",
  "file": "f083.html",
  "g": "10. Layout",
  "t": "Resizing columns",
  "d": "Drag the right-hand edge of a header to change its width. Widths can be saved with getLayout() and restored later."
 },
 {
  "n": 85,
  "no": "10-2",
  "file": "f084.html",
  "g": "10. Layout",
  "t": "Double-click a boundary to fit the contents",
  "d": "Double-click the edge of a header and the column is sized to its contents, exactly as a spreadsheet does. It measures what is on the screen rather than the raw value, so money with separators and coded names are not clipped."
 },
 {
  "n": 86,
  "no": "10-3",
  "file": "f085.html",
  "g": "10. Layout",
  "t": "Reordering and hiding columns",
  "d": "Drag a header by its text to move the column — sorting lives on the icons, so the two never collide. Columns you do not need can be unticked in the column panel."
 },
 {
  "n": 87,
  "no": "10-4",
  "file": "f086.html",
  "g": "10. Layout",
  "t": "Freezing columns",
  "d": "Pin the first few columns so they do not scroll away sideways. On a wide table it keeps you from losing track of which row you are reading. Mark the columns with freeze:1 and switch freezeOn on."
 },
 {
  "n": 88,
  "no": "10-5",
  "file": "f087.html",
  "g": "10. Layout",
  "t": "Building group headers (two rows)",
  "d": "Gather related columns under a shared caption and the header becomes two rows. Give the columns the same group name and that is all. On a wide table it tells you at a glance what kind of value each column holds."
 },
 {
  "n": 89,
  "no": "10-6",
  "file": "f088.html",
  "g": "10. Layout",
  "t": "Breaking a header across lines",
  "d": "For headers too long to fit. A \\n in the label breaks the line exactly there; headerWrap:true lets the grid wrap it for you to suit the width."
 },
 {
  "n": 90,
  "no": "10-7",
  "file": "f089.html",
  "g": "10. Layout",
  "t": "Long headers end in an ellipsis",
  "d": "A label wider than its column is trimmed with .... Room is always kept for the sort arrows and the filter funnel, so a long caption can never push the controls out of reach."
 },
 {
  "n": 91,
  "no": "10-8",
  "file": "f090.html",
  "g": "10. Layout",
  "t": "How many rows to a page",
  "d": "The Per page control offers 10, 25, 50, 100 and everything. Choose everything and the page buttons disappear, leaving one continuous list."
 },
 {
  "n": 92,
  "no": "10-9",
  "file": "f091.html",
  "g": "10. Layout",
  "t": "Scrolling through a large set quickly",
  "d": "Turn this on when you would rather scroll through thousands of rows than page through them. Only the part you can see is drawn, so five thousand rows scroll without stuttering."
 },
 {
  "n": 93,
  "no": "10-10",
  "file": "f092.html",
  "g": "10. Layout",
  "t": "Saving and restoring the layout",
  "d": "Everything the user arranged — column order, widths, hidden columns, sorting, filters and page size — can be lifted out in one object and put back next time. If the column set has changed in the meantime, anything that no longer exists is quietly skipped rather than breaking the screen."
 },
 {
  "n": 94,
  "no": "10-11",
  "file": "f115.html",
  "g": "10. Layout",
  "t": "Grid height — fixed, capped, or filling the window",
  "d": "A grid holds a fixed 420px unless told otherwise, so it no longer shrinks when there are few rows. height sets that size, maxHeight caps how far it may grow instead, and height:&#39;fill&#39; stretches it to the bottom of the window."
 },
 {
  "n": 95,
  "no": "11-1",
  "file": "f093.html",
  "g": "11. Modals",
  "t": "The detail and edit windows build themselves",
  "d": "These are the windows for viewing a row in full or editing it. There is no form to write — the fields come from the column definitions, so adding a column adds a field to the window as well."
 },
 {
  "n": 96,
  "no": "11-2",
  "file": "f094.html",
  "g": "11. Modals",
  "t": "The right editor for each field",
  "d": "Each field gets an editor to suit its column type — a select for coded values, a multi-line box for long text, a date picker for dates and a number box for figures."
 },
 {
  "n": 97,
  "no": "11-3",
  "file": "f095.html",
  "g": "11. Modals",
  "t": "Read-only fields are still shown",
  "d": "A column marked editor:false appears in the window read-only. The value is not hidden — it is shown but cannot be changed — so reference details such as an employee number or a registration date stay in view."
 },
 {
  "n": 98,
  "no": "11-4",
  "file": "f096.html",
  "g": "11. Modals",
  "t": "Saving from the window is checked too",
  "d": "Save in the window runs the same validation as typing into the cell. A value that fails is not saved and the problem is pointed out."
 },
 {
  "n": 99,
  "no": "12.1-1",
  "file": "f097.html",
  "g": "12.1 Themes",
  "t": "Switching themes (eleven of them)",
  "d": "One call to setTheme() recolours the whole grid. Themes are applied per grid, so two tables on one page can look quite different, and nothing else on the page is touched."
 },
 {
  "n": 100,
  "no": "12.2-1",
  "file": "f098.html",
  "g": "12.2 Fonts",
  "t": "Separate fonts for the header and the body",
  "d": "Size, family, weight and slant can be set for the header and the body independently. Give only the parts you care about and the rest is left alone; pass null for one property to reset just that one."
 },
 {
  "n": 101,
  "no": "12.2-2",
  "file": "f099.html",
  "g": "12.2 Fonts",
  "t": "Changing the font size",
  "d": "Enlarge the body font and the row numbers and numeric cells grow with it. They are sized in proportion rather than fixed, so the table stays balanced at any size — handy for a zoom control or a per-user preference."
 },
 {
  "n": 102,
  "no": "12.3-1",
  "file": "f100.html",
  "g": "12.3 Display options",
  "t": "Choosing what appears in the footer",
  "d": "The footer carries the row count, the page list and Per page, in that order. Any of them can be switched off, and turning all three off removes the footer altogether."
 },
 {
  "n": 103,
  "no": "12.3-2",
  "file": "f101.html",
  "g": "12.3 Display options",
  "t": "Messages appear inside the grid",
  "d": "Notices such as \"copied\" or \"nothing to undo\" appear in the middle of the grid concerned rather than in a corner of the page. With several grids about, there is no doubt which one is talking."
 },
 {
  "n": 104,
  "no": "13-1",
  "file": "f102.html",
  "g": "13. Server integration",
  "t": "Fetching a page at a time from the server",
  "d": "For sets too large to load in one go. Supply dataSource and the sorting, filtering, search and paging arrive as a single request object, ready to be turned into SQL."
 },
 {
  "n": 105,
  "no": "13-2",
  "file": "f103.html",
  "g": "13. Server integration",
  "t": "Loading state, failures and reloading",
  "d": "A loading overlay covers the grid while a request is out. If it fails, dataError tells you and the previous rows stay on screen, so a momentary error does not blank the table. reload() repeats the request with the conditions unchanged."
 },
 {
  "n": 106,
  "no": "13-3",
  "file": "f104.html",
  "g": "13. Server integration",
  "t": "The same question is not asked twice",
  "d": "Values for the filter popup (filterSource) and autocomplete candidates (acSource) are remembered once fetched. Ask for the same thing again and no request goes out, which keeps the chatter down."
 },
 {
  "n": 107,
  "no": "14-1",
  "file": "f105.html",
  "g": "14. Other",
  "t": "Undo and redo (Ctrl+Z · Ctrl+Y)",
  "d": "Every change is recorded as you make it. Ctrl+Z steps back one at a time and Ctrl+Y steps forward again, and each step says which action it is undoing."
 },
 {
  "n": 108,
  "no": "14-2",
  "file": "f106.html",
  "g": "14. Other",
  "t": "Row ids are filled in for you",
  "d": "Rows arriving without an id, or sharing one, are sorted out as they load. A number once used is never handed out again, so deleting a row and adding another cannot leave you with two of the same. Supply genId to number them your own way."
 },
 {
  "n": 109,
  "no": "14-3",
  "file": "f107.html",
  "g": "14. Other",
  "t": "Adding and removing photos",
  "d": "A type:'images' column holds photos. Pick them with ＋ Add or drop the files onto the cell. Hover a file name for a larger preview, and remove one with ✕."
 },
 {
  "n": 110,
  "no": "14-4",
  "file": "f108.html",
  "g": "14. Other",
  "t": "Choosing how photos are sent",
  "d": "imageMode decides when a photo goes to the server and in what shape. The four modes and their server-side code are covered one by one under 8.1 Image transfer."
 },
 {
  "n": 111,
  "no": "14-5",
  "file": "f109.html",
  "g": "14. Other",
  "t": "Trimming the right-click menu (contextMenu)",
  "d": "Entries you do not want can be dropped from the right-click menu. Anything you do not mention stays, and the setting sits on top of the permissions — turn something on here and it still will not appear without the right to use it."
 },
 {
  "n": 112,
  "no": "14-6",
  "file": "f110.html",
  "g": "14. Other",
  "t": "The menu setting cannot outrank a permission",
  "d": "Entries you do not mention stay visible — the setting lists what to hide rather than what to show. And because it sits on top of the permissions, switching something on here will not bring it back if the user has no right to it."
 },
 {
  "n": 113,
  "no": "14-7",
  "file": "f111.html",
  "g": "14. Other",
  "t": "Switching the right-click menu off entirely",
  "d": "With contextMenu:false the grid menu is not shown at all and the browser's own menu appears as usual — useful when the page needs the browser features left alone."
 },
 {
  "n": 114,
  "no": "14-8",
  "file": "f112.html",
  "g": "14. Other",
  "t": "Translating the built-in messages (i18n)",
  "d": "The built-in wording is English. Pass options.i18n with just the entries you want changed and the rest stay as they are. A function value lets a message vary with the situation."
 },
 {
  "n": 115,
  "no": "14-9",
  "file": "f113.html",
  "g": "14. Other",
  "t": "Wiring up your own buttons (controls)",
  "d": "Point options.controls at buttons and labels of your own and the grid keeps their pressed state and their text up to date as things change. Use it when you would rather build your own toolbar than use the grid's."
 }
];
